runtime: python27
api_version: 1
threadsafe: true
default_expiration: '1s'
handlers:
  - url: /(.*\.(css|html|ico|js|svg|otf))
    static_files: fountain.finance-web/\1
    upload: fountain.finance-web/(.*\.(css|html|ico|js|svg|otf))
  - url: /.*
    static_files: fountain.finance-web/index.html
    upload: fountain.finance-web/index.html
    secure: always
